DROP TABLE IF EXISTS app_roles CASCADE;
DROP TABLE IF EXISTS app_role_permissions CASCADE;
DROP TABLE IF EXISTS app_permissions CASCADE;
DROP TABLE IF EXISTS user_app_roles CASCADE;
DROP VIEW  IF EXISTS user_views CASCADE;
DROP FUNCTION  IF EXISTS fn_user_views CASCADE;
